ALTER TABLE TB_PINQUIRY ADD CONSTRAINT PQNA_MEMNO_FK FOREIGN KEY (MEM_NO) REFERENCES TB_MEMBER(MEM_NO);

ALTER TABLE TB_PINQUIRY ADD CONSTRAINT PQNA_PNO_FK FOREIGN KEY (PRODUCT_NO) REFERENCES TB_PRODUCT_UD(PRODUCT_NO);

ALTER TABLE TB_PINQUIRY ADD CONSTRAINT PQNA_MGRNO_FK FOREIGN KEY(MANAGER_NO) REFERENCES TB_MANAGER_ID(MANAGER_NO);


ALTER TABLE TB_REVIEW ADD CONSTRAINT REVIEW_PNO_FK FOREIGN KEY 
(PRODUCT_NO) REFERENCES TB_PRODUCT_UD (PRODUCT_NO);

ALTER TABLE TB_REVIEW ADD CONSTRAINT REVIEW_MNO_FK FOREIGN KEY 
(MEM_NO) REFERENCES TB_MEMBER (MEM_NO);

ALTER TABLE TB_REVIEW ADD CONSTRAINT REVIEW_MGRNO_FK FOREIGN KEY(MANAGER_NO) REFERENCES TB_MANAGER_ID (MANAGER_NO);


ALTER TABLE SP_ORDERPRODUCT ADD CONSTRAINT SP_ORDERNO_FK FOREIGN KEY (ORDER_NO) REFERENCES SPMY_ORDER (ORDER_NO);

ALTER TABLE SP_ORDERPRODUCT ADD CONSTRAINT SP_ORDERPNO_FK FOREIGN KEY (PRODUCT_NO) REFERENCES TB_PRODUCT_UD(PRODUCT_NO);